name: Deploy static site from frontend/

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site from frontend/ folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: frontend

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
