name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]  # Change this if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload frontend directory
        uses: actions/upload-pages-artifact@v2
        with:
          path: frontend

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
